# PHP
phpfpm:
  restart: always
  extends:
    file: php-fpm.yml
    service: phpfpm
  links:
    - db:db

# NGINX
nginx:
  restart: always
  image: nginx
  ports:
    - '80:80'
    - '443:443'
  links:
    - phpfpm:phpfpm
  volumes:
    - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    - ./app:/var/www/html
    - ./log/nginx:/var/log/nginx

# MYSQL
db:
  restart: always
  image: mysql:latest
  ports:
    - '3307:3306'
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: aaron
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: book
  volumes:
    - ./mysql/databases:/var/lib/mysql
    - ./log/mysql:/var/log/mysql
